export const shows = [
  { id: 'soundwave', category: '페스티벌', title: '서울 사운드 웨이브 2026', english: 'SOUND\nWAVE', sub: 'SEOUL MUSIC FESTIVAL', place: '올림픽공원 88잔디마당', date: '2026.10.17 – 10.18', dates: ['2026-10-17', '2026-10-18'], time: '18:00', price: 99000, image: 'festival.jpg', tone: 'lime', tag: '얼리버드', day: '17', month: 'OCT', duration: '180분', description: '도시의 소음이 음악이 되는 순간. 가을 하늘 아래 펼쳐지는 다채로운 사운드와 함께 특별한 하루를 만나보세요.' },
  { id: 'bluehour', category: '콘서트', title: '블루 아워 : The Midnight Live', english: 'the\nblue hour.', sub: 'A NIGHT TO REMEMBER', place: '블루스퀘어 마스터카드홀', date: '2026.10.24 – 10.25', dates: ['2026-10-24', '2026-10-25'], time: '19:00', price: 88000, image: 'night.jpg', tone: 'blue', tag: '단독 판매', day: '24', month: 'OCT', duration: '120분', description: '낮과 밤의 경계, 가장 푸른 시간. 몽환적인 신스 사운드와 함께 오래 기억될 밤을 만들어보세요.' },
  { id: 'afterglow', category: '콘서트', title: '애프터글로우 : Autumn Tour', english: 'AFTER\nGLOW', sub: '2026 AUTUMN TOUR', place: 'YES24 라이브홀', date: '2026.11.07 – 11.08', dates: ['2026-11-07', '2026-11-08'], time: '18:30', price: 77000, image: 'live.jpg', tone: 'pink', tag: '예매 중', day: '07', month: 'NOV', duration: '110분', description: '음악이 끝나도 남아 있는 온기. 선명한 밴드 사운드와 진솔한 목소리를 가까이에서 만나세요.' },
  { id: 'cityjazz', category: '재즈·클래식', title: '시티 재즈 나이트', english: 'CITY\nJAZZ\nNIGHTS', sub: 'GOOD MUSIC. GREAT COMPANY.', place: '노들섬 라이브하우스', date: '2026.11.14 – 11.15', dates: ['2026-11-14', '2026-11-15'], time: '19:30', price: 66000, image: 'lights.jpg', tone: 'gold', tag: '추천 공연', day: '14', month: 'NOV', duration: '100분', description: '도시의 불빛, 한강의 바람, 그리고 재즈. 따뜻한 즉흥 연주로 가득 채우는 여유로운 가을밤.' },
  { id: 'letter', category: '뮤지컬·연극', title: '뮤지컬 : 마지막 편지', english: 'THE LAST\nLETTER', sub: 'AN ORIGINAL MUSICAL', place: '대학로 아트홀', date: '2026.11.21 – 11.22', dates: ['2026-11-21', '2026-11-22'], time: '17:00', price: 55000, image: 'lights.jpg', tone: 'gold', tag: '새로운 공연', day: '21', month: 'NOV', duration: '100분', description: '전하지 못한 한 통의 편지에서 시작되는 이야기. 따뜻한 선율과 배우들의 목소리가 무대 위에서 만납니다.' },
];
export type Show = typeof shows[number];
export const categories = ['전체', '콘서트', '페스티벌', '뮤지컬·연극', '재즈·클래식'];
export const won = (amount: number) => amount.toLocaleString('ko-KR') + '원';
export const formatDate = (date: string) => new Intl.DateTimeFormat('ko-KR', { month: 'long', day: 'numeric', weekday: 'short', timeZone: 'Asia/Seoul' }).format(new Date(date + 'T12:00:00+09:00'));
